emperor(turza, simulation).
emperor(sadhin, html).
emperor(sadhin, css).
emperor(udoy, sleep).
emperor(rajesh, love).
emperor(minhaj, superman).
emperor(turza, css).
emperor(tanu, deeplearning).
emperor(bipro, css).
emperor(munna, html).
emperor(tanvir, poet).
emperor(arif, math).
like(ismail, dating).
like(rajesh, dating).
like(minhaj, photograph).
